version: 2
jobs:
  build:
    steps:
      - checkout

      - run:
          name: yarn-install
          command: yarn

      - run:
          name: compile
          command: make build

      - run:
          name: test
          command: yarn test
